### ISSUE TITLE
Fix Heroku automated deployment

### ISSUE THREAD

**Issue by DanielJohnston** [nineworldsgeekfest/scheduler#13]
Something's wrong. Find out what and make it work. Woo!

**Comment by DanielJohnston** [comment]
Current thinking is that the postgres database hasn't been set up properly on heroku. db:migrate has to be run manually, I suspect. So I'm going to add the git repo and the heroku instructions to my dev VM, then use that to `heroku run rake db:migrate`.

**Comment by DanielJohnston** [comment]
I've added heroku toolbelt to my local dev instance and pushed a new branch to heroku, with a heroku-required gem added. For some reason, running `heroku run rake` claims to generate the missing secrets.yml file but absolutely doesn't.

**Comment by DanielJohnston** [comment]
For reference, `git push -f heroku local-topic-branch:refs/heads/master` is your friend for pushing a non-master branch to heroku's live branch.

**Comment by DanielJohnston** [comment]
Further reference on the heroku fix. The final link was http://jaylee.com/heroku-missing-secret_toekn-and-secret_key_base-for-production/ which added a line to `production.rb` that generated a secret token on heroku at install. Other than that, used https://devcenter.heroku.com/articles/getting-started-with-rails4 for general info on working with Heroku and Rails, and connected an existing heroku dyno using `heroku git:remote -a scheduler9w`. May write this up as a very brief 'deploy to heroku' guide.

**Comment by mattjuk** [comment]
Ah, yes. If heroku is running as production, then you need to use the environment variable (as the secrets.yml file states)
