### ISSUE TITLE
Fix config/database.yml to not just use the current user in dev/test

### ISSUE THREAD

**Issue by mattjuk** [nineworldsgeekfest/scheduler#24]
Currently config/database.yml has an insane configuration for dev/test which assumes that Postgres will do no or peer authentication in the current user context to localhost. This should be fixed.

**Comment by DanielJohnston** [comment]
The way I've handled db on local previously is changing all of the db passwords in database.yml to point to environment variables, and each developer has to set them up themselves.

**Comment by mattjuk** [comment]
Fine by me, but in which case db:setup needs to not do dev and test at the same time, because you can't use database_url to override both things on one command.

**Comment by DanielJohnston** [comment]
Looked into it a bit more. Env vars is the 'Heroku' way of doing things, and using .gitignore to withhold secrets.yml is the more 'Rails' approach. Looking through my course materials, I was taught to always put production passwords and API keys in env vars, but we never set up proper db logins for dev or test, so it's a new one on me. Do you want to take this, or should I? There will likely be a requirement to mess around with Travis to get it working again after changing the test db setup.

**Comment by mattjuk** [comment]
I'm not convinced Travis will be affected, because it uses database.yml.travis anyway.

**Comment by mattjuk** [comment]
Ok. Having looked more carefully at this, I think the correct way to solve this is via Developer Documentation rather than changing the current behaviour.

**Comment by mattjuk** [comment]
Closed per pull request having fixed the documentation issue.
