### ISSUE TITLE
DB schema incorrectly collapses many-many to many-one relationships

### ISSUE THREAD

**Issue by mattjuk** [nineworldsgeekfest/scheduler#28]
Currently, the `programs` table has direct foreign key relationships with `flags`, `people` and `track`. This is incorrect as it implies that these are many-one relationships rather than many-many.

**Comment by DanielJohnston** [comment]
Inclined to try and resolve by rolling back the `rails g scaffold` with a `rails d` and recreating.

**Comment by mattjuk** [comment]
Disagree. Suggest `rails g migration` to remove the foreign keys first of all, then a second migration to add the new many-many relations.

**Comment by mattjuk** [comment]
(Or do a manual migration which merges the two things together.)

**Comment by DanielJohnston** [comment]
I *thought* there was a way of creating many-to-many as part of rails g, but the Googles are telling me that `rails g migration` is the way forward, cf http://stackoverflow.com/questions/26865865/scaffolding-table-obtained-by-many-to-many-relationship.

**Comment by DanielJohnston** [comment]
Does #29 fix this?

**Comment by mattjuk** [comment]
Fixed by #29
