### ISSUE TITLE
Switch Coveralls to Code Climate

### ISSUE THREAD

**Issue by DanielJohnston** [nineworldsgeekfest/scheduler#33]
Find out why the Coveralls badge [![Coverage Status](https://coveralls.io/repos/nineworldsgeekfest/scheduler/badge.svg?branch=master&service=github)](https://coveralls.io/github/nineworldsgeekfest/scheduler?branch=master) isn't displaying properly if it continues to show 'unknown', and fix it.

**Comment by DanielJohnston** [comment]
(horrible feeling it might be because Coveralls doesn't count pull requests as CI against the target branch, but I guess we'll see. Vague memory of running into a similar issue previously)

**Comment by DanielJohnston** [comment]
There is literally nothing on Google other than some timeliness issues, and nothing in the Coveralls docs. It's been a week with no improvement. I've tried setting failure thresholds in the settings to see if that helps. If that doesn't help after another couple of commits I'll raise an issue in Coveralls.io tracker at https://github.com/lemurheavy/coveralls-public/issues.

**Comment by DanielJohnston** [comment]
Moving to Code Climate. This involves 1) Changing to Code Climate badges on the README, 2) Adding Code Coverage setup to the project in Travis, 3) Setting up commenting on pull requests.

**Comment by DanielJohnston** [comment]
Commenting on Pull Requests doesn't make much sense in Code Climate. It looks like they want me to enter a token to post comments to the request using my profile, despite them already having access to my account in order to link up the repo in the first place. Gonna try a pull request and see what happens.

**Comment by mattjuk** [comment]
Still busted...
