### ISSUE TITLE
Write initial structure plans

### ISSUE THREAD

**Issue by danwhitston** [nineworldsgeekfest/scheduler#4]
Current thinking is Rails + DB + React + Bootstrap, test apps (rspec for backend, ?? for frontend). This needs more research, then a TDD'd 'touch' from one end to the other.

**Comment by DanielJohnston** [comment]
The bootstrap and react-rails gems look interesting in this regard, although not so sure they taste great together. Some info at http://www.openmindedinnovations.com/blogs/3-ways-to-integrate-ruby-on-rails-react-flux and https://github.com/reactjs/react-rails
