### ISSUE TITLE
Pass conferences scaffold tests

### ISSUE THREAD

**Issue by danwhitston** [nineworldsgeekfest/scheduler#49]
Add valid and invalid attributes to the conferences spec in order to enable the scaffold tests to pass.

**Comment by DanielJohnston** [comment]
Question: why would `ConferencesController POST #create with invalid params assigns a newly created but unsaved conference as @conference` be expected to work in the first place? As in, is the point that you can create an invalid conference and it only causes an error upon attempting to save?

For reference, the test failure is `expected #<Conference id: 7, name: "1000", start_date: nil, end_date: nil, created_at: "2016-01-23 14:46:10", updated_at: "2016-01-23 14:46:10"> to be a new Conference(id: integer, name: string, start_date: date, end_date: date, created_at: datetime, updated_at: datetime)`

**Comment by DanielJohnston** [comment]
Minor note. Looks like validations in the model might be the issue. Adding now...
