### ISSUE TITLE
Document dev process

### ISSUE THREAD

**Issue by danwhitston** [nineworldsgeekfest/scheduler#5]
Detail the git process, acceptance testing, and team roles if appropriate.

**Comment by DanielJohnston** [comment]
Pointing Jay_tech at the dev process documentation issue

**Comment by DanielJohnston** [comment]
Suggest writing up the process in README.md and moving to docs folder when it becomes unwieldy.

**Comment by rycudasakkran** [comment]
Documentation probably wants to cover a "Start hacking on this" section
